### ISSUE TITLE
debug 的时候Pangle SDK VERIFIED，release的时候 SDK: NOT VERIFIED

### ISSUE THREAD

**Issue by KeJunMao** [toponteam/TopOn-Android-Demo#4]
使用 flutter 开发，在插件中直接log，` TTADSDK: com.bytedance.sdk.openadsdk.p@a74f431 ` 也是存在的

部分log：
```
03-02 18:13:55.560 21829 21942 I anythink: NetworkName: Pangle(Tiktok)  (v3.4.1.2)
03-02 18:13:55.560 21829 21942 I anythink: SDK: NOT VERIFIED
03-02 18:13:55.560 21829 21942 I anythink: Providers : VERIFIED
03-02 18:13:55.560 21829 21942 E anythink: Status: Fail
```

topon sdk version 5.7.11
pangle sdk version 3.4.1.2

使用的是中国区

具体表现如下：
- `flutter build apk` no
- `flutter run --release` ok
- `flutter build apk --debug` ok
- android studio 打开 android 目录直接 build apk(s) ok

同样问题的还有百度，其他广告sdk没问题。

如果您还需要别的日志帮助我判断问题所在请指使，感谢您的帮助！

**Comment by zhangshiren** [comment]
可以确认一下两个路径是否被混淆了：
（1）穿山甲：com.bytedance.sdk.openadsdk.TTAdSdk
（2）百度：com.baidu.mobads.utils.XAdSDKFoundationFacade
如果只是被混淆了，但是广告请求和正常的就不会有问题。
如果想要保证Vertify的话就将com.bytedance.sdk.**和com.baidu.mobads.** keep 住即可

**Comment by KeJunMao** [comment]
感谢，已经解决
